class DisplayedString {
  static Map zhtw = {
    'create repo': '創建新學習集',
    'add tags': '新增標籤',
    'repos': '學習集',
    'title': '標題',
    'tags': '標籤',
    'title error': '請輸入標題',
    'tag error': '請輸入標籤',
    'add': '新增',
    'new tag': '新標籤',
    'duplicated': '已有此標籤',
    'edit': '編輯',
    'delete': '刪除',
    'more': '更多',
    'delete flashcard alert title': '刪除單字卡',
    'delete flashcard alert content': '你確定要刪除此單字卡嗎？',
    'cancel': '取消',
    'confirm': '確認',
    'learn': '學習',
    'answer correct': '答對了！',
    'continue': '繼續',
    'answer incorrect': '答錯了！',
    'correct answer': '正確答案:',
    'quiz settings': '設定',
    'enable definition selection quiz': '顯示定義選擇題',
    'enable definition short answer quiz': '顯示定義簡答題',
    'enable word selection quiz': '顯示單字選擇題',
    'enable word short answer quiz': '顯示單字簡答題',
    'enable kanji short answer quiz': '顯示漢字簡答題',
    'enable answer audio': '答案語音',
    'only show favorite': '只顯示最愛',
    'dont know': '不知道',
    'enter word': '請輸入單字',
    'enter definition': '請輸入定義',
    'no card': '找不到單字卡',
    'repository': '學習集',
    'sort by': '排序依據',
    'increasing': '標題: A 到 Z',
    'decreasing': '標題: Z 到 A',
    'repo settings': '學習集設定',
    'memorized': '已學習',
    'rename': '重新命名',
    'edit repo': '編輯學習集',
    'edit tag list': '編輯標籤',
    'delete alert title': '刪除學習集',
    'delete alert content': '你確定要刪除此學習集嗎？',
    'delete tag title': '刪除標籤',
    'delete tag content': '你確定要刪除此標籤嗎？',
    'new title': '新標題',
    'select tags': '選擇標籤',
    'clear': '清除',
    'select all': '全選',
    'original':'創建順序',
    'reset progress': '重置進度',
    'reset flashcard progress alert': '你確定要重置此單字卡的進度嗎',
    'reset progress alert': '你確定要重置此學習集的所有進度嗎',
    'no enough cards': '請添加至少五張單字卡',
    'select word type': '選擇詞性',
    'tag filter': '篩選標籤',
    'profile': '個人資料',
    'sign out': '登出',
    'help': '幫助',
    'language': '語言',
    'theme': '主題',
    'email': '電子信箱',
    'google sign in': '使用 google 帳號登入',
    'zhtw': '繁體中文',
    'blue': '藍色',
    'statistics': '統計',
    'developing': '開發中',
    'or get started': '或直接開始',
  };
}
