class DisplayedString {
  static Map zhtw = {
    'create repo': '創建新學習集',
    'add tags': '新增標籤',
    'repos': '學習集',
    'title': '標題',
    'tags': '標籤',
    'title error': '請輸入標題',
    'tag error': '請輸入標籤',
    'add': '新增',
    'new tag': '新標籤',
    'duplicated': '已有此標籤',
    'edit': '編輯',
    'delete': '刪除',
    'more': '更多',
    'delete flashcard alert title': '刪除單字卡',
    'delete flashcard alert content': '你確定要刪除此單字卡嗎？',
    'cancel': '取消',
    'confirm': '確認',
    'learn': '學習',
    'answer correct': '答對了！',
    'continue': '繼續',
    'answer incorrect': '答錯了！',
    'correct answer': '正確答案:',
    'quiz settings': '設定',
    'enable definition selection quiz': '顯示定義選擇題',
    'enable definition short answer quiz': '顯示定義簡答題',
    'enable word selection quiz': '顯示單字選擇題',
    'enable word short answer quiz': '顯示單字簡答題',
    'enable kanji short answer quiz': '顯示漢字簡答題',
    'enable answer audio': '答案語音',
    'only show favorite': '只顯示最愛',
    'dont know': '不知道',
    'enter word': '請輸入單字',
    'enter definition':'請輸入定義',
  };
}
